[package]
name = "cchat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# TODO: Remove unused tokio features
tokio = { version = "1.31.0", features = ["full"] }